### ISSUE TITLE
odahuflowctl local. don't check conn to API, if the user is not logged in.

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow#158]
for odahuflowctl local. error with localhost.
If the user is not logged in then we shouldn't check conn. to API.

**Comment by BPylypenko** [comment]
didn't reproduced on macOS odahu v. 1.3.0-rc1.

**Comment by keshamin** [comment]
We found out that the behavior it expected: parse files passed as CLI arguments. If `ModelTraining` or `ToolchainIntegration` are not found there, it tries to pull them from API. It user is not logged it, well, it is expected that we cannot proceed until they fix it. 

Also, currently if training/toolchain are fetched from API server, an appropriate message shows up  in `--verbose` mode only. After discussion with @BPylypenko (reporter) we decided that CLI should print the message anyway, with or without verbose.

**Comment by keshamin** [comment]
Fixed by #356
