### ISSUE TITLE
hide (bash/powershell) code of odahuflowctl completion

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow#201]
hide code of command that should be executed.
![image](https://user-images.githubusercontent.com/49116723/79334228-8bda9980-7f28-11ea-8964-22036791d3af.png)

**Comment by keshamin** [comment]
@BPylypenko  This is from `odahuflowctl completion --help`:
```
Usage: odahuflowctl completion [OPTIONS] [[bash|fish|zsh|powershell]]
  Output odahuflowctl completion code to stdout.

  Load the zsh completion in the current shell:
      source <(odahuflowctl completion zsh)

Options:
  --help  Show this message and exit.
```

That is, it has to print the actual completion code to the output for `source <(odahuflowctl completion zsh)` to work. Is it unexpected behavior?

**Comment by keshamin** [comment]
I created a PR https://github.com/odahu/odahu-docs/pull/83 to docs that explains the basic usage of `odahiflowctl completion` command.

**Comment by keshamin** [comment]
Closed this issue as **not a bug**.
