### ISSUE TITLE
failed training with mlflow-gpu toolchain

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow#230]
Training fails if it's running with toolchain: mlflow-gpu.
![image](https://user-images.githubusercontent.com/49116723/81841180-b84afb00-9552-11ea-866b-a4d0ace3755a.png)
[training-mlflow-gpu.training.odahuflow.txt](https://github.com/odahu/odahu-flow/files/4633952/training-mlflow-gpu.training.odahuflow.txt)

**Comment by vlad-tokarev** [comment]
@BPylypenko  Please, provide information to reproduce beheviour. Training yaml file would be good

**Comment by BPylypenko** [comment]
@vlad-tokarev  added file in description.

**Comment by BPylypenko** [comment]
No bug: training (wine) is not adapted to GPU.
