### ISSUE TITLE
the 'kind' parameter should remain in API

### ISSUE THREAD

**Issue by karbyshevds** [odahu/odahu-flow#282]
**Description**
to create training, connection through cli, sdk you must specify 'kind' parameter in file. But when this command returns or you call, for example, 'connection get' command the answer is without 'kind' parameter.

**Expected behaviour:**
- when you get connection, training, packaging and so on through Swagger (from API) it should be with the 'kind' parameter in output.

**Comment by BPylypenko** [comment]
Not a bug. It's expected behavior.
