### ISSUE TITLE
can submit training with invalid name and version through 'YAML' tab

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow#342]
**Describe**
during training creation through Web UI (by `+ New` button) this name and version shown as invalid.
for example, `11-23$`, `11-234-`

**To Reproduce**
Steps to reproduce the behavior for UI:
1. create training
2. update training through `YAML` tab  with new invalid name and version.

**Expected behavior**
Should show error that model name and model version are invalid

**Actual behavior**
Creates training and the state is unknown infinitely.

**Screenshots**
![image](https://user-images.githubusercontent.com/49116723/93340633-ba410580-f835-11ea-981e-9af0148fa437.png)

**Comment by keshamin** [comment]
Fixed by #349
