### ISSUE TITLE
azureblob type of connection needs only relative path of container in uri

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow#345]
**Describe the bug**
`azureblob` type conection requires in `URI` relative path of container to the resource.

connections which follow on the screenshots:
with `wine` connection as a data connection, the training succeded, but with either `wine-azure-full-uri`, `wine-azure` or `wine-azure-1`, the training failed. the only change for training is the data connection.

**Screenshots**
![Screenshot 2020-09-18 at 00 37 23](https://user-images.githubusercontent.com/49116723/93590619-8392f880-f9b7-11ea-82cb-0f6bd19a4b20.png)
![image](https://user-images.githubusercontent.com/49116723/93600051-c066eb80-f9c7-11ea-9f52-bb652d03ec31.png)

**training logs**
[wine-azure-check.log.txt](https://github.com/odahu/odahu-ui/files/5245727/wine-azure-check.log.txt)
[wine-azure-1-check.log.txt](https://github.com/odahu/odahu-ui/files/5245728/wine-azure-1-check.log.txt)
![image](https://user-images.githubusercontent.com/49116723/93601802-6d426800-f9ca-11ea-91e4-26869495edaa.png)

**Comment by keshamin** [comment]
Closed by #353
