### ISSUE TITLE
Refactor deployment/route CRD controllers to use Knative Service, not Configuration

### ISSUE THREAD

**Issue by keshamin** [odahu/odahu-flow#347]
Currently to deploy a model:
1. we create Knative Configuration to deploy a model
1. we track if the Knative Revision is created and ready
1. we create a K8s service for that revision
1. we copy Endpoints from Knative Revision to our K8s Service
1. we create an Istio VirtualService that routes requests from Istio Ingress to the corresponding K8s service.

This can be simplified as follows:
1. we create Knative Service
1. we wait for the Knative Service to get up and running
1. we create an Istio VirtualService that routes requests from Istio Ingress to the Knative Service.

This guide demonstrates a simplified implementation: https://knative.dev/docs/serving/samples/knative-routing-go/index.html

**Comment by vlad-tokarev** [comment]
Knative manages Istio Ingress internally to turn traffic between Application pod svc and `Knative Activator` pod.
So in this case:
> we create an Istio VirtualService that routes requests from Istio Ingress to the Knative Service.

We may face problems that this feature will conflict with Knative ingress managing
