### ISSUE TITLE
not correct desc of error provided that invalid version of Model Training given

### ISSUE THREAD

**Issue by karbyshevds** [odahu/odahu-flow#348]
if you give invalid version of training, this error is shown. The Model training version is required field (cannot be empty).
![image](https://user-images.githubusercontent.com/763662/84963630-97a63000-b112-11ea-8b4b-bf11b957035e.png)

**Comment by keshamin** [comment]
Figured out that it is fixed on UI side as shown above. But the API indeed accepts invalid model version which causes that Training cannot create in K8s. DB-K8s syncer tries to sync it endlessly.
