### ISSUE TITLE
gppi predict fails on GPPI self-check

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow#391]
**description**
when I test gppi model through `odahuflowctl gppi test` cmd, it returns that model can be packaged or deployed
but when I run `predict` it gives the error that GPPI self-check failed.

**To Reproduce**
1. run local training and get created artifact (succeeded)
2. check that the model training gppi is OK (`odahuflowctl gppi -m <model path> test`)
3. run prediction (`odahuflowctl gppi -m <model path> predict [OPTIONS]`)

**Expected behavior**
outputs prediction to the specified file

**Actual behavior**
gives Error that `GPPI self-check failed`

**screenshots**
![image](https://user-images.githubusercontent.com/49116723/94669621-29c8f180-031a-11eb-944a-15f266e79f47.png)

**desktop**
 - OS: macOS 10.15.6
 - cli, sdk versions: 1.3.0-rc1

**additional context**

**Comment by keshamin** [comment]
@BPylypenko I cannot reproduce it on locally-trained wine model. Please send me your trained artifact for investigation.

**Comment by keshamin** [comment]
Tried with [training_artifact.tar.gz](https://github.com/odahu/odahu-flow/files/5311397/training_artifact.tar.gz), that @BPylypenko provided and still cannot reproduce it. Prediction works well for me.

**Comment by BPylypenko** [comment]
the problem was that I used `~` instead of an absolute path for `odahuflowctl gppi -m <model path> predict` for `[OPTIONS]`.

But after the restart, it didn't reproduce.
