### ISSUE TITLE
redundant createdAt and updatedAt keys for training, packaging, deployment

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow#394]
**Describe the bug**
there are two `createdAt` and `updatedAt` keys

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/49116723/94797749-3c5e2c00-03e9-11eb-8688-6af6c1a7df18.png)

**expected behaviour**
should be only one `createdAt` and `updatedAt` (not in the `status`)

**expected behaviour**
there are two `createdAt` and `updatedAt` keys

**Comment by keshamin** [comment]
These fields are indeed redundant. They are gonna be deprecated since 1.3 and planned to be completely removed in 1.4.

**Comment by BPylypenko** [comment]
As I see, this issue is not resolved, for now, so I think we should just put tag: `1.4` and place to `To Do` column so that we won't forget to do that or create another task (feature) for that and put the link to this task there.

**Comment by vlad-tokarev** [comment]
@BPylypenko, @keshamin 
Currently, these fields are deprecated
What do you think about deferring their removal to ODAHU 2.0 release? Motivation is not to break backward compatibility for clients in a minor release
