### ISSUE TITLE
concurrent `bulk apply` cmd for the same entity, cause execution only 1st manifest

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow#415]
**description**
when you (almost) simultaneously try to create or update an entity, it leads that the 2nd request is rejected. As entity already exists.

**Expected behavior**
the second change should be applied and output should indicate that resource was updated

**Actual behavior**
gives error that entity already exists

**Screenshots**
![image](https://user-images.githubusercontent.com/49116723/96992668-e0437f00-1532-11eb-8046-740f38624636.png)

**Comment by karbyshevds** [comment]
This is expected behaviour, closing
