### ISSUE TITLE
gives help window when you don't pass the option flag, but value

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow#418]
**description**
when you miss the option for `odahuflowctl gppi` and pass a value for that option, It gives you the help window instead of the error that you did not pass the option, in this case `--gppi-model-path`.

**command**
try to run 

``` bash
odahuflowctl gppi <path> predict "~/request.json" ~/.odahuflow/
```

**Expected behavior**
gives the error that `--gppi-model-path/-m OR ODAHUFLOW_GPPI_MODEL_PATH env var must be provided`

**Actual behavior**
gives the help window

**Screenshots**
![image](https://user-images.githubusercontent.com/49116723/97217989-b7d8b080-17d0-11eb-92cb-39aeced879e2.png)

**Comment by karbyshevds** [comment]
It's expected behaviour, closing.

**Comment by karbyshevds** [comment]
It's expected behaviour, closing.
