### ISSUE TITLE
redundant `mlflow-gpu` toolchain on cluster

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow#435]
**description**
`mlflow` & `mlflow-gpu` share completely the same specification and `mlflow` toolchain can be used to run training on gpu.

The `mlflow-gpu` toolchain is redundant and should be deleted.

**Expected behavior**
there is only one toolchain which could be used for cpu and gpu trainings

**Actual behavior**
there is two toolchain with the same spec and any of which could be used for cpu and gpu trainings

**Comment by karbyshevds** [comment]
@vlad-tokarev. I can't see that we pass any toolchain specs during deployment, are you sure that it can be fixed in automation?

**Comment by karbyshevds** [comment]
Extra spec should be deleted from helm chart:
https://github.com/odahu/odahu-trainer/blob/1f2dec6cc743d5a7921fd7d4e9884d13c3f158cd/helms/odahu-flow-mlflow/templates/mlflow-integration.yaml#L10

odahu-flow-examples should be updated to exclude missing toolchain spec.

**Comment by BPylypenko** [comment]
It's already removed from the cluster.

Now it remains to remove it from helm chart. ([comment](https://github.com/odahu/odahu-flow/issues/435#issuecomment-731170027))

**Comment by owlleg6** [comment]
mlflow-gpu spec is already deleted from develop branch
