### ISSUE TITLE
Local Training fails because of No module named 'scipy'

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow#462]
**Description**
Local Training fails because of `No module named 'scipy'`. But the scipy package is downloaded during `conda env update ... `, what could be seen in logs (stdout).

**Steps to Reproduce**
1. run local training: 

```
odahuflowctl --verbose local train run --train-id local-host-default-template -f "packages/tests/e2e/robot/tests/local/resources/artifacts/odahuflow/file/training.default.artifact.template.json"
```

1.  look at stdout. 

**Actual result**
The local training fails saying that `ModuleNotFoundError: No module named 'scipy'`

**Expected result**
The training is finished successfully.

**Attachments**
_**training spec:**_  [training.default.artifact.template.txt](https://github.com/odahu/odahu-flow/files/5795274/training.default.artifact.template.txt)
_**logs:**_  [stdout.txt](https://github.com/odahu/odahu-flow/files/5795262/stdout.txt)

**Comment by keshamin** [comment]
Bug was reproduced. Investigating...
