### ISSUE TITLE
max length of the model deployment ID should be 46

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow#579]
**Description**
Under the hood, for each deployment, a ConfigMap is created with ID == `modelDeployment.ID + "-opa-policy".` This ID is indicated in the label, and the label value cannot exceed 63 characters.

So the ID max length for the model deployment should be no more than 52 chars.

Update! should be no more than **46** chars.

Logs extract:
```
Message:               Revision creation failed with message: Revision.serving.knative.dev "wine-odahu-ui-object-storage-default-workdir-ju-ui-deploy-cvknb" is invalid: metadata.labels: Invalid value: "wine-odahu-ui-object-storage-default-workdir-ju-ui-deploy-opa-policy": must be no more than 63 characters.
```

**Steps to Reproduce**
1. Create model deployment with more than 46 characters.
2. Notice that deployment doesn't go to state `Ready`

**Actual result**
the max length of model deployment is **63**.

**Expected result**
the max length of model deployment is **46**.

**Comment by lev-titov** [comment]
When length of model deployment id in interval of 52 < id < 63 we got an error from operator: 
`Revision creation failed with message: Revision.serving.knative.dev "wine-odahu-ui-object-storage-default-workdir-ju-ui-deploy-cvknb" is invalid: metadata.labels: Invalid value: "wine-odahu-ui-object-storage-default-workdir-ju-ui-deploy-opa-policy": must be no more than 63 characters` and "-opa-policy" must be concedered
But when its in interval 46 < id < 53 we are getting error message with no info about why this id is not valid, so for now we just manually limits id length to 46
