### ISSUE TITLE
When the predict command is run for model from docker CLI packager, the error is returned `TypeError: Object of type 'ndarray' is not JSON serializable`

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow#586]
**Description**
When the predict command is run for model from docker CLI packager, the error is returned `TypeError: Object of type 'ndarray' is not JSON serializable`

**Steps to Reproduce**
1. Run valid odahu training and wait until it succeeds.
2. Create model packaging with "docker-cli" packager and wait until it succeeds.
3. Make docker-pull of the result image for packaging from step (2).
4. Make prediction from model:
    ```
    docker run -it --rm \
    --mount type=bind,source="$(pwd)",target=/volume \
    --net host <model packaging result image> \
    predict /volume/request.json /volume

**Actual result**
The error is returned: `TypeError: Object of type 'ndarray' is not JSON serializable`

**Expected result**
There is no error and the model returns the expected response.

**Attachments**
[logs.docker-cli-packager.txt](https://github.com/odahu/odahu-flow/files/6553201/logs.docker-cli-packager.txt)
![image](https://user-images.githubusercontent.com/49116723/127648006-2c668304-015d-49c1-a81d-eabae3a51222.png)


**Environment**
ODAHU version: 1.5.0-rc7

**Comment by alinaignatiuk** [comment]
Need to reproduce and update status if needed

**Comment by BPylypenko** [comment]
It reproduces. I have added the screenshot and the ODAHU version it was reproduced on.
